name: Skapa checklista

on:
  workflow_dispatch:  # Gör det möjligt att köra manuellt från GitHub-gränssnittet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Installera requests
        run: pip install requests

      - name: Kör skapa_checklista.py
        run: python skapa_checklista.py

      - name: Committa resultatet (om filen finns)
        run: |
          if [ -f data/checklista.json ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add data/checklista.json
            git commit -m "✅ Uppdaterade checklista"
            git push
          else
            echo "❌ Inget att committa – filen data/checklista.json saknas."
          fi
