name: Skapa checklista

on:
  workflow_dispatch:  # Gör det möjligt att köra manuellt från GitHub-gränssnittet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Klona repo
        uses: actions/checkout@v3

      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Installera requests
        run: pip install requests

      - name: Exportera API-nyckel
        run: echo "OCP_APIM_SUBSCRIPTION_KEY=${{ secrets.OCP_APIM_SUBSCRIPTION_KEY }}" >> $GITHUB_ENV

      - name: Kör skapa_checklista.py
        run: python skapa_checklista.py


      - name: Committa resultatet (om filen ändrats)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/checklista.json
          if git diff --cached --quiet; then
            echo "⚠️ Inget att committa – inga ändringar."
          else
            git commit -m "✅ Uppdaterade checklista"
            git push
          fi
